#base image
FROM node

#set working directory
RUN mkdir /usr/src/app

#Copy all files from current directory to docker
COPY . /usr/src/app

WORKDIR /usr/src/app

#add .'path/node_module/.bin' to $PATH
ENV PATH /usr/src/app/node_module/.bin:$PATH

#install and cache app dependencies
RUN yarn

#start app
CMD ["npm","start"]