export const CHANEL = {
  API_URL: `${process.env.REACT_APP_SOCKET_URL}`,
  LOG_OUT: "__logout",
  SPEAK_USER_ID: "__speakerUserId",
  LIST_ONLINE: "__listOnline",
  ROOM_CHAT: "__roomChat:id=",
  SEND_TYPING_CHAT: "__sendTypingChat",
  RECEIVE_TYPING_CHAT: "__typingChatRoom:id=",
  MY_INBOX: "__myInbox:id=",
  OPEN_MY_BOX_CHAT: "__openBoxChat",
  RECEIVE_BOX_CHAT: "__receiveBoxChat:id=",
  RECEIVE_LIKE_NEW_FEED: "__newFeed:id=",
  ON_READ_ROOM: "__onReadRoom",
  RECEIVE_READ_ROOM: "__receiveReadRoom:id=",
};
