# OUTPUT_LANG_INDEX start from 0
generator-localization-user:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1-070pYbrLXebgIJUx97VPNwxpnXgZD9w11PeVxwG1jI GID_ID=User OUTPUT_FOLDER=../src/i18n/locales/ja/defaults.json